FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

# Install Python 3.10
RUN apt-get update && apt-get install -y python3.10 python3-pip
RUN apt-get update && apt-get install -y build-essential python3-dev
RUN python3.10 -m pip install --upgrade pip setuptools wheel
RUN apt install git -y
WORKDIR /code
COPY . /code
COPY config /code/config

RUN python3.10 -m pip install -e .
RUN huggingface-cli download unsloth/Llama-3.2-11B-Vision-Instruct

ENTRYPOINT python3.10 -m AGISwarm.llm_instruct_ms --config-name config.yaml
