FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04
WORKDIR /code
COPY . /code
COPY config /code/config
RUN apt-get update && apt-get install -y python3.10 python3-pip &&\
    apt-get update && apt-get install -y build-essential python3-dev&&\
    python3.10 -m pip install --upgrade pip setuptools wheel&&\
    apt install git -y&&\
    python3.10 -m pip install -e .&&\
    huggingface-cli download unsloth/Llama-3.2-11B-Vision-Instruct

ENTRYPOINT python3.10 -m AGISwarm.llm_instruct_ms --config-name config.yaml
