%YAML 1.1
---

hf_model_name: !!str "Orenguteng/Llama-3-8B-Lexi-Uncensored-GGUF"
tokenizer_name: "meta-llama/Meta-Llama-3-8B-Instruct"

engine: !!str VLLMEngine
engine_config:

defaults:
  - gui_config: default
  - uvicorn_config: default