%YAML 1.1
---

hf_model_name: !!str RichardErkhov/IlyaGusev_-_saiga_llama3_8b-4bits
tokenizer_name: !!str RichardErkhov/IlyaGusev_-_saiga_llama3_8b-4bits

engine: !!str HFEngine
engine_config:

defaults:
  - gui_config: default
  - uvicorn_config: default
