%YAML 1.1
---

hf_model_name: !!str "Orenguteng/Llama-3-8B-Lexi-Uncensored-GGUF"
tokenizer_name: !!str "meta-llama/Meta-Llama-3-8B-Instruct"

engine: !!str LlamaCppEngine
engine_config:
  filename: !!str "*Q4_K_M.gguf"
  n_gpu_layers: 0

defaults:
  - gui_config: default
  - uvicorn_config: default
