%YAML 1.1
---

hf_model_name: !!str "meta-llama/Meta-Llama-3-8B-Instruct"
tokenizer_name: !!str "meta-llama/Meta-Llama-3-8B-Instruct"

engine: !!str VLLMEngine
engine_config:

defaults:
  - gui_config: default
  - uvicorn_config: default
