
%YAML 1.1
---

hf_model_name: !!str "Vikhrmodels/Vikhr-7B-instruct_0.2"
tokenizer_name: "Vikhrmodels/Vikhr-7B-instruct_0.2"

engine: !!str VLLMEngine
engine_config:

defaults:
  - gui_config: default
  - uvicorn_config: default
