
%YAML 1.1
---
engine: !!str VLLMEngine

model_name: !!str "Vikhrmodels/Vikhr-7B-instruct_0.2"
tokenizer_name: "Vikhrmodels/Vikhr-7B-instruct_0.2"

host: !!str "127.0.0.1"
port: !!int 8000

gui_title: !!str "Vikhr-7B-instruct_0.2"
default_max_new_tokens: !!int 1000
default_temperature: !!float 0.6
default_top_p: !!float 0.95
default_repetition_penalty: !!float 1.2
default_frequency_penalty: !!float 0.0
default_presence_penalty: !!float 0.0
