default_sampling_config:
  max_new_tokens: !!int 1000
  temperature: !!float 0.6
  top_p: !!float 0.95
  repetition_penalty: !!float 1.2
  frequency_penalty: !!float 0.0
  presence_penalty: !!float 0.0
